// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZUg7sa9wOw5WlZ99IO6HeING5ibPaCyw',
    appId: '1:20424580808:web:22bb620a5a8d620c23cffd',
    messagingSenderId: '20424580808',
    projectId: 'sust-face-attendance-app',
    authDomain: 'sust-face-attendance-app.firebaseapp.com',
    storageBucket: 'sust-face-attendance-app.firebasestorage.app',
    measurementId: 'G-CZKKLPJYP1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwYhB04l0OYQLHv75O0FQFR5gzQtEZ83I',
    appId: '1:20424580808:android:294f900b7358740023cffd',
    messagingSenderId: '20424580808',
    projectId: 'sust-face-attendance-app',
    storageBucket: 'sust-face-attendance-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhBs6nFVaiEujTP4l0SNZMfi2pfPDDeUk',
    appId: '1:20424580808:ios:b2df5750b9e56e4823cffd',
    messagingSenderId: '20424580808',
    projectId: 'sust-face-attendance-app',
    storageBucket: 'sust-face-attendance-app.firebasestorage.app',
    iosBundleId: 'com.example.attendanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhBs6nFVaiEujTP4l0SNZMfi2pfPDDeUk',
    appId: '1:20424580808:ios:b2df5750b9e56e4823cffd',
    messagingSenderId: '20424580808',
    projectId: 'sust-face-attendance-app',
    storageBucket: 'sust-face-attendance-app.firebasestorage.app',
    iosBundleId: 'com.example.attendanceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZUg7sa9wOw5WlZ99IO6HeING5ibPaCyw',
    appId: '1:20424580808:web:33bf95d054aa3e9123cffd',
    messagingSenderId: '20424580808',
    projectId: 'sust-face-attendance-app',
    authDomain: 'sust-face-attendance-app.firebaseapp.com',
    storageBucket: 'sust-face-attendance-app.firebasestorage.app',
    measurementId: 'G-9ZH1P61KML',
  );
}
